"""Adicionando tabela favoritos

Revision ID: 2e9a37fccf17
Revises: 351508aaa548
Create Date: 2026-06-05 22:21:21.162576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9a37fccf17'
down_revision: Union[str, Sequence[str], None] = '351508aaa548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_lugar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='usuarios'
    )
    op.create_index('idx_favorito_lugar', 'favoritos', ['id_lugar'], unique=False, schema='usuarios')
    op.drop_table('alembic_version_lugares')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_lugares',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_lugares_pkc'))
    )
    op.drop_index('idx_favorito_lugar', table_name='favoritos', schema='usuarios')
    op.drop_table('favoritos', schema='usuarios')
    op.drop_table('usuarios', schema='usuarios')
    # ### end Alembic commands ###
